### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by abers** [3ximus/gruvbox-gtk#1]
Hi sorry to be a pain again. Where should I place the files from this if I want them to show up as an option in Plasma's GNOME Application Style settings? There is option to "install a local theme" but it expects a compressed file.

**Comment by 3ximus** [comment]
I think you can use either ~/.themes/ or /usr/share/themes if im not mistaken.

**Comment by 3ximus** [comment]
Yeah, a quick google search confirmed what i said xD

**Comment by abers** [comment]
doh - I tried "/themes" and forgot the dot!
