### ISSUE TITLE
missing scripts/utils.sh

### ISSUE THREAD

**Issue by Twitch0125** [3ximus/gruvbox-gtk#2]
I've ran 
Make
Make install
and I get this in the terminal

rm -rf "gtk-3.0/dist"
rm -f "gtk-3.0/gtk.gresource"
rm -rf "gtk-3.20/dist"
rm -f "gtk-3.20/gtk.gresource"
rm -rf "/home/kaleb/Desktop/gruvbox-gtk/dist"
mkdir -p gtk-3.0/dist
sassc -I "gtk-3.0/scss" "gtk-3.0/scss/gtk.scss" "gtk-3.0/dist/gtk.css"
sassc -I "gtk-3.0/scss" "gtk-3.0/scss/gtk-dark.scss" "gtk-3.0/dist/gtk-dark.css"
glib-compile-resources --sourcedir="gtk-3.0" "gtk-3.0/gtk.gresource.xml"
mkdir -p gtk-3.20/dist
sassc -I "gtk-3.20/scss" "gtk-3.20/scss/gtk.scss" "gtk-3.20/dist/gtk.css"
sassc -I "gtk-3.20/scss" "gtk-3.20/scss/gtk-dark.scss" "gtk-3.20/dist/gtk-dark.css"
glib-compile-resources --sourcedir="gtk-3.20" "gtk-3.20/gtk.gresource.xml"
scripts/utils.sh install "/usr/share/themes/Numix"
/bin/sh: scripts/utils.sh: No such file or directory
make: *** [Makefile:56: install] Error 127

**Comment by dcfreire** [comment]
Same here

**Comment by mjkpolo** [comment]
Same

**Comment by ghost** [comment]
Just put the files in /usr/share/themes

**Comment by exorcist365** [comment]
^

**Comment by 3ximus** [comment]
> Just put the files in /usr/share/themes
