### ISSUE TITLE
What license is this distributed by?

### ISSUE THREAD

**Issue by kgilmer** [3ximus/gruvbox-gtk#3]

**Comment by 3ximus** [comment]
There is no license, this is just an auto-generated theme created with oomox

**Comment by kgilmer** [comment]
Thanks @3ximus .  Well I am creating a [debian package from your work](https://launchpad.net/~regolith-linux/+archive/ubuntu/unstable/+sourcepub/11531350/+listing-archive-extra) for use in Regolith and have to specify a license.  So I set it as gpl-3.  LMK if this is not what you want.
